name: Release
on:
  #push:
  #  branches:
  #    - master
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Lint files
        run: pnpm run lint
      - name: Typecheck files
        run: pnpm run typecheck
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Run unit tests
        run: pnpm run test run --coverage
  build-release:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build package
        run: pnpm run build
      - name: Set NPM token & GitHub config
        run: |
          npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
          git config user.name "Kuatsu CI/CD"
          git config user.email "null@kuatsu.de"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Release
        run: pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.CICD_PAT }}
